export const PIPELINE_ITEM_TYPE = {
    SCHEDULE: 'SCHEDULE',
    SENSOR: 'SENSOR',
    SWITCH: 'SWITCH',
    CHECK_SWITCH: 'CHECK_SWITCH',
    DELAY: 'DELAY',
    NETWORK: 'NETWORK',
    NOTIFICATION: 'NOTIFICATION',
};
