namespace Homo.IotApi
{
    public partial class ERROR_CODE
    {
        public static string OAUTH_REDIRECT_URI_NOT_IN_WHITLIST = "OAUTH_REDIRECT_URI_NOT_IN_WHITLIST";
        public static string OAUTH_TYPE_ONLY_SUPPORT_CODE = "OAUTH_TYPE_ONLY_SUPPORT_CODE";
        public static string OAUTH_CLIENT_ID_NOT_FOUND = "OAUTH_CLIENT_ID_NOT_FOUND";
        public static string OAUTH_CODE_EXPIRED = "OAUTH_CODE_EXPIRED";
        public static string DEVICE_STATE_EXISTS = "DEVICE_STATE_EXISTS";
        public static string TAPPAY_TRANSACTION_ERROR = "TAPPAY_TRANSACTION_ERROR";
        public static string DUPLICATE_SUBSCRIBE = "DUPLICATE_SUBSCRIBE";
        public static string DUPLICATE_OAUTH_CLIENT_ID = "DUPLICATE_OAUTH_CLIENT_ID";
        public static string DEVICE_OAUTH_CLIENT_EXISTS = "DEVICE_OAUTH_CLIENT_EXISTS";
        public static string NO_SUBSCRIPTION = "NO_SUBSCRIPTION";
        public static string OAUTH_CLIENT_SECRET_ERROR = "OAUTH_CLIENT_SECRET_ERROR";
        public static string TOO_MANY_REQUEST = "TOO_MANY_REQUEST";
        public static string DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND";
        public static string DEIVCE_WITHOUT_MCU = "DEIVCE_WITHOUT_MCU";
        public static string OVER_PRICING_PLAN = "OVER_PRICING_PLAN";
        public static string TRIGGER_DEST_DEVICE_ID_REQUIRED = "TRIGGER_DEST_DEVICE_ID_REQUIRED";
        public static string TRIGGER_DEST_DEVICE_TARGET_STATE_REQUIRED = "TRIGGER_DEST_DEVICE_TARGET_STATE_REQUIRED";
        public static string TRIGGER_DEST_PIN_REQUIRED = "TRIGGER_DEST_PIN_REQUIRED";
        public static string TRIGGER_NOTIFICATION_NEEDS_CONTACT_INFORMATION = "TRIGGER_NOTIFICATION_NEEDS_CONTACT_INFORMATION";
        public static string TRIGGER_NOTIFICATION_OVER_USING = "TRIGGER_NOTIFICATION_OVER_USING";
        public static string PIPELINE_CONNECTOR_EXISTS = "PIPELINE_CONNECTOR_EXISTS";
        public static string PIPELINE_INFINITY_LOOP = "PIPELINE_INFINITY_LOOP";
        public static string OFFLINE_NOTIFICATION_USAGE_LIMIT = "OFFLINE_NOTIFICATION_USAGE_LIMIT";
        public static string UNALLOW_PIPELINE_HEAD_TYPE = "UNALLOW_PIPELINE_HEAD_TYPE";
        public static string SWITCH_PIPELINE_INVALID_PAYLOAD_DEVICE_ID_IS_REQUIRED = "SWITCH_PIPELINE_INVALID_PAYLOAD_DEVICE_ID_IS_REQUIRED";
        public static string SWITCH_PIPELINE_INVALID_PAYLOAD_PIN_IS_REQUIRED = "SWITCH_PIPELINE_INVALID_PAYLOAD_PIN_IS_REQUIRED";
        public static string SWITCH_PIPELINE_INVALID_PAYLOAD_STATUS_IS_REQUIRED = "SWITCH_PIPELINE_INVALID_PAYLOAD_STATUS_IS_REQUIRED";
        public static string DELAY_PIPELINE_INVALID = "DELAY_PIPELINE_INVALID";
        public static string NETWORK_PIPELINE_INVALID_URL_IS_REQUIRED = "NETWORK_PIPELINE_INVALID_URL_IS_REQUIRED";
        public static string NETWORK_PIPELINE_INVALID_METHOD_IS_REQUIRED = "NETWORK_PIPELINE_INVALID_METHOD_IS_REQUIRED";
        public static string NETWORK_PIPELINE_INVALID_CONTENT_TYPE_IS_REQUIRED = "NETWORK_PIPELINE_INVALID_CONTENT_TYPE_IS_REQUIRED";
        public static string NETWORK_PIPELINE_INVALID_PAYLOAD_RESPONSE_STATUS_IS_REQUIRED_IN_OTHER_CONTENT_TYPE = "NETWORK_PIPELINE_INVALID_PAYLOAD_RESPONSE_STATUS_IS_REQUIRED_IN_OTHER_CONTENT_TYPE";
        public static string NETWORK_PIPELINE_INVALID_PAYLOAD_OPERATOR_IS_REQUIRED_IN_EXTRACT_RESPONSE_BODY = "NETWORK_PIPELINE_INVALID_PAYLOAD_OPERATOR_IS_REQUIRED_IN_EXTRACT_RESPONSE_BODY";
        public static string NETWORK_PIPELINE_INVALID_PAYLOAD_VALUE_IS_REQUIRED_IN_EXTRACT_RESPONSE_BODY = "NETWORK_PIPELINE_INVALID_PAYLOAD_VALUE_IS_REQUIRED_IN_EXTRACT_RESPONSE_BODY";
        public static string NOTIFICATION_PIPELINE_INVALID_PAYLOAD_NOTIFICATION_TYPE_IS_REQUIRED = "NOTIFICATION_PIPELINE_INVALID_PAYLOAD_NOTIFICATION_TYPE_IS_REQUIRED";
        public static string NOTIFICATION_PIPELINE_INVALID_PAYLOAD_EMAIL_IS_REQUIRED = "NOTIFICATION_PIPELINE_INVALID_PAYLOAD_EMAIL_IS_REQUIRED";
        public static string NOTIFICATION_PIPELINE_INVALID_PAYLOAD_PHONE_IS_REQUIRED = "NOTIFICATION_PIPELINE_INVALID_PAYLOAD_PHONE_IS_REQUIRED";
        public static string NOTIFICATION_PIPELINE_INVALID_PAYLOAD_MESSAGE_IS_REQUIRED = "NOTIFICATION_PIPELINE_INVALID_PAYLOAD_MESSAGE_IS_REQUIRED";
        public static string NOTIFICATION_PIPELINE_INVALID_PAYLOAD_MESSAGE_MAX_LENGTH_50 = "NOTIFICATION_PIPELINE_INVALID_PAYLOAD_MESSAGE_MAX_LENGTH_50";
        public static string INVALID_PIPELINE_ITEM_TYPE_IN_MID = "INVALID_PIPELINE_ITEM_TYPE_IN_MID";

        public static string PIPELINE_COULD_NOT_ALLOW_MULTIPLE_HEAD = "PIPELINE_COULD_NOT_ALLOW_MULTIPLE_HEAD";
        public static string NOT_ALLOW_PIPELINE_TYPE = "NOT_ALLOW_PIPELINE_TYPE";
        public static string SENSOR_PIPELINE_INVALID_PAYLOAD_DEVICE_ID_IS_REQUIRED = "SENSOR_PIPELINE_INVALID_PAYLOAD_DEVICE_ID_IS_REQUIRED";
        public static string SENSOR_PIPELINE_INVALID_PAYLOAD_PIN_IS_REQUIRED = "SENSOR_PIPELINE_INVALID_PAYLOAD_PIN_IS_REQUIRED";
        public static string SENSOR_PIPELINE_INVALID_PAYLOAD_LAST_ROWS_IS_REQUIRED = "SENSOR_PIPELINE_INVALID_PAYLOAD_LAST_ROWS_IS_REQUIRED";
        public static string SENSOR_PIPELINE_INVALID_PAYLOAD_STATIC_METHOD_IS_REQUIRED = "SENSOR_PIPELINE_INVALID_PAYLOAD_STATIC_METHOD_IS_REQUIRED";
        public static string SENSOR_PIPELINE_INVALID_PAYLOAD_OPERATOR_IS_REQUIRED = "SENSOR_PIPELINE_INVALID_PAYLOAD_OPERATOR_IS_REQUIRED";
        public static string SENSOR_PIPELINE_INVALID_PAYLOAD_THRESHOLD_IS_REQUIRED = "SENSOR_PIPELINE_INVALID_PAYLOAD_THRESHOLD_IS_REQUIRED";
        public static string SCHEDULE_PIPELINE_INVALID_PAYLOAD_VALUE_IS_REQUIRED = "SCHEDULE_PIPELINE_INVALID_PAYLOAD_VALUE_IS_REQUIRED";


    }
}